rbacEnable: {{RBAC_ENABLE}}
# disable grafana until we have something to see:
deployGrafana: false
# disable because not needed in team-frontend namespace:
deployExporterNode: false
deployKubelets: false
deployKubeScheduler: false
deployKubeControllerManager: false
deployKubeState: false
deployCoreDNS: false
deployKubeDNS: false
deployKubeEtcd: false
prometheus:
  # prometheusLabelValue: prometheus-team-frontend
  # # alertingEndpoints:
  # # - name: prometheus-team-frontend-alertmanager
  # #   namespace: team-frontend
  # #   port: http
  resources:
    requests:
      memory: 400Mi
  rules:
    value:
      - name: team-frontend-rules
        rules:
          - alert: FrontendApiDown
            expr: absent(up{job="team-frontend-api-api"}) or (count(up{job="team-frontend-api-api"} == 1) BY (cluster) == 0)
            for: 5m
            labels:
              severity: critical
            annotations:
              description: There is no running frontend api. Deployments and replication controllers are not making progress.
              summary: Frontend API is down
  # externalUrl: https://prometheus.{{CLUSTER_HOST}}
  externalUrl: http://127.0.0.1:9190
alertmanager:
  # prometheusLabelValue: prometheus-team-frontend
  config:
    global:
      slack_api_url: "{{SLACK_API_URL}}"
    route:
      receiver: default-receiver
      repeat_interval: 3h
      routes:
        - match:
            alertname: DeadMansSwitch
          repeat_interval: 5m
          receiver: deadmansswitch
    receivers:
      - name: deadmansswitch
      - name: default-receiver
        slack_configs:
          - channel: "#frontend"
            send_resolved: true
  # to have clickable links in the gui:          
  # externalUrl: https://alertmanager.{{CLUSTER_HOST}}
  externalUrl: http://127.0.0.1:9193

