apiVersion: v1
appVersion: 0.2.8
description: Istio Helm chart for Kubernetes
home: https://istio.io/
icon: https://raw.githubusercontent.com/istio/istio.github.io/master/favicons/mstile-150x150.png
maintainers:
- email: lachlan.evenson@microsoft.com
  name: lachie83
name: istio
sources:
- https://github.com/istio/istio
version: 0.2.8-chart2
