dependencies:
  - name: exporter-kube-api
    version: 0.1.0
    repository: file://./charts.cloudposse.com/incubator

  - name: exporter-kube-controller-manager
    version: 0.1.0
    repository: file://./exporter-kube-controller-manager

  - name: exporter-coredns
    version: 0.1.0
    repository: file://./charts.cloudposse.com/incubator

#  - name: exporter-kube-dns
#    version: 0.1.0
#    repository: file://./charts.cloudposse.com/incubator

  - name: exporter-kube-etcd
    version: 0.1.0
    repository: file://./charts.cloudposse.com/incubator

  - name: exporter-kube-scheduler
    version: 0.1.0
    repository: file://./charts.cloudposse.com/incubator

  - name: exporter-kubelets
    version: 0.1.0
    repository: file://./charts.cloudposse.com/incubator

  - name: exporter-kubernetes
    version: 0.1.0
    repository: file://./charts.cloudposse.com/incubator

