apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-server
  namespace: drone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
      - image: drone/drone:0.8-alpine
        imagePullPolicy: Always
        name: drone-server
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
          # Persist our configs in an SQLite DB in here
          - mountPath: /var/lib/drone
            name: db-volume
          # Enables Docker in Docker
          - mountPath: /var/run/docker.sock
            name: docker-socket
        resources:
          requests:
            cpu: 40m
            memory: 32Mi
        env:
        - name: DRONE_HOST
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.host
        - name: DRONE_OPEN
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.open
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: server.secret
        - name: DRONE_ADMIN
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.admin
        - name: DRONE_GITHUB
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.remote.github
        - name: DRONE_GITHUB_CLIENT
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.remote.github.client
        - name: DRONE_GITHUB_SECRET
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.remote.github.secret
        - name: DRONE_BITBUCKET
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.remote.bitbucket
        - name: DRONE_BITBUCKET_CLIENT
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.remote.bitbucket.client
        - name: DRONE_BITBUCKET_SECRET
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.remote.bitbucket.secret

        - name: DRONE_DEBUG
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.debug
      volumes:
      - name: db-volume
        hostPath:
          # directory location on host
          path: /var/tmp/drone
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
