{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- if or (and .Values.ingress.annotations ) (not .Values.ingress.tls) }}
  annotations:
    {{- if not .Values.ingress.tls }}
    ingress.kubernetes.io/ssl-redirect: 'false'
    {{- end }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Values.prometheus }}
    release: {{ .Release.Name }}
  {{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
  {{- end }}
  name: {{ template "fullname" . }}
spec:
  rules:
    - host: "{{ .Values.ingress.fqdn }}"
      http:
        paths:
          - path: "{{ .Values.routePrefix }}"
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: 9090
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
{{- end }}
