apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    kubernetes.io/name: KubeRegistry
spec:
  selector:
    k8s-app: kube-registry
  type: ClusterIP
  ports:
  - name: registry
    port: 80
    protocol: TCP
    targetPort: 5000
