apiVersion: v1
appVersion: 1.7.1
description: Flux is a tool that automatically ensures that the state of a cluster
  matches what is specified in version control
engine: gotpl
home: https://weave.works
icon: https://landscape.cncf.io/logos/flux.svg
maintainers:
- email: stefan@weave.works
  name: stefanprodan
name: flux
sources:
- https://github.com/weaveworks/flux
version: 0.3.4
