---
# cluster > dns
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-cluster-ingress-dns
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.0.0/16
    ports:
    - protocol: UDP
      port: 53
---
# prometheus > dns monitoring
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-prometheus-ingress-dns
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          purpose: monitoring
    ports:
    - protocol: TCP
      port: 9153
---
# - dns egress > kubernetes api
# - dns udp egress
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-dns-egress-kubernetes
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
  egress:
  # had to open up to all, but wanted to use the part that is commented out below
  - to: []
#    - ipBlock:
#        cidr: 10.96.0.0/8
#    ports:
#    - protocol: TCP
#      port: 443
#  - to:
#    - namespaceSelector:
#        matchLabels:
#          name: kube-system
#    ports:
#    - protocol: UDP
---
# cluster ingress > kubernetes api
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cluster-ingress-kubernetes
  namespace: kube-system
spec:
  podSelector: {}
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 443
