---
# allow nginx ingress > kibana egress > elasticsearch
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kibana
  namespace: logging
spec:
  podSelector:
    matchLabels:
      app: kibana
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
    - namespaceSelector:
        matchLabels:
          purpose: public-ingress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: elasticsearch
---
# allow kibana ingress > elasticsearch
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-filebeat
  namespace: logging
spec:
  podSelector:
    matchLabels:
      app: filebeat
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: elasticsearch
---
# allow kibana ingress > elasticsearch
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-elasticsearch
  namespace: logging
spec:
  podSelector:
    matchLabels:
      app: elasticsearch
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: kibana
    - podSelector:
        matchLabels:
          app: filebeat
